"""add_installation_id_to_pr_reviews

Revision ID: 56d198f22187
Revises: e5f2bb331013
Create Date: 2026-05-14 02:24:39.539872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d198f22187'
down_revision: Union[str, Sequence[str], None] = 'e5f2bb331013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pr_reviews', sa.Column('installation_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr_reviews', 'installation_id')
    # ### end Alembic commands ###
