"""composite_unique_review_finding

Revision ID: e5f2bb331013
Revises: e6cb41cac4c4
Create Date: 2026-05-13 23:12:38.966538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f2bb331013'
down_revision: Union[str, Sequence[str], None] = 'e6cb41cac4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('findings_finding_hash_key'), 'findings', type_='unique')
    op.create_unique_constraint('uq_review_finding', 'findings', ['pr_review_id', 'finding_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_finding', 'findings', type_='unique')
    op.create_unique_constraint(op.f('findings_finding_hash_key'), 'findings', ['finding_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
