"""drop_critic_columns

Revision ID: e6cb41cac4c4
Revises: eafd158f8628
Create Date: 2026-05-13 23:05:40.896761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cb41cac4c4'
down_revision: Union[str, Sequence[str], None] = 'eafd158f8628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'critic_reasoning')
    op.drop_column('findings', 'critic_conf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('critic_conf', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('critic_reasoning', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
